name: Start/Stop Railway Service

on:
  schedule:
    - cron: "0 8 * * *"  # Start pukul 08:00 UTC
    - cron: "0 22 * * *"  # Stop pukul 22:00 UTC

jobs:
  control-railway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Login to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: echo $RAILWAY_TOKEN | railway login

      - name: Start or Stop Service
        env:
          CURRENT_HOUR: ${{ github.event.schedule }}
        run: |
          HOUR=$(date -u +"%H")
          if [ "$HOUR" -eq 8 ]; then
            echo "Starting Railway Service..."
            railway up --project 3f4f2470-d29c-441c-ac43-f70651d11222
          elif [ "$HOUR" -eq 22 ]; then
            echo "Stopping Railway Service..."
            railway down --project 3f4f2470-d29c-441c-ac43-f70651d11222
          else
            echo "No matching schedule."
          fi
